from snakemake.utils import min_version
min_version("8.11.3")

configfile: "/home/marc/projects/genome_annotation/config/config.yaml"

samples = glob_wildcards(config["rna_reads_directory"]+"/{sample}_{group}.fastq.gz")

rule all:
    input:
        get_final_output()

include:    "functions.smk"
include:    "rules/repeatmasker.smk"
include:    "rules/BRAKER3.smk"



