#This is the configuration file for the rna_seq_worklow.
#You have to modify this file to your needs and fill out every option (if not stated otherwise), 
#but do not add or remove options if your not 100% sure what you are doing!

#INPUT

#Absolute path to your RNAseq reads directory. sample names should have the following format: ID_GROUP.fastq
seq_dir: /home/marc/projects/genome_annotation/resources/rna_seq_reads/wesdi_denovo

#Absolute path to the reference genome fasta
ref_genome: /home/marc/projects/genome_annotation/resources/genome_assembly/wesdi_denovo/westerdykella_dispersa.fasta

#The ID for this analyis run
Run ID: wesdi_denovo

#Absolute path to the genome annotation file (GTF) 
gtf: /home/marc/projects/genome_annotation/workflow/results/braker/westerdykella_dispersa/braker.gtf

#Sample info file 
sample_info: /home/marc/projects/rna_seq_workflow/resources/wesdi_denovo_info.tsv

#Contrast .csv file containing a "treatment" column and a "control" column specifying what conditions should be contrasted. 
contrast :  /home/marc/projects/rna_seq_workflow/resources/wesdi_contrast.csv

#Absoulte path to the reference amino acid sequences
protein_fasta: /home/marc/projects/genome_annotation/workflow/results/braker/westerdykella_dispersa/braker.aa

#EGGNOG-MAPPER V2 results (Optional)
eggnog_results: /home/marc/projects/rna_seq_workflow/results/functional_annotations/wesdi_denovo/eggnog/MM_t865abr3.emapper.annotations.tsv


#PARAMETERS

#Computational ressources
threads:  4

#Gene ontology analysis (yes or "")
GO_terms: "yes"

#cutadapt
Trimming: "no" #yes or no
adapter_r1: "A" #adapter sequence forward reads
adapter_r2: "A" #adapter sequence reverse reads
quality_cutoff: ""  #quality filtering (leave empty for no filtering)

#Strandness ["",0] for Unstranded, ["FR",1] for Stranded or ["RF",2] for Reverse Stranded
Strandness: ["RF",2]

#Gene set enrichment analysis (GSEA) (Currently not employed)
GSEA gene set: GO_Biological_Process_2023