#This is the configuration file for the rna_seq_worklow.
#You have to modify this file to your needs and fill out every option (if not stated otherwise), 
#but do not add or remove options if your not 100% sure what you are doing!

#INPUT

#Absolute path to your RNAseq reads directory. sample names should have the following format: ID_GROUP.fastq
seq_dir: /home/nanopore/projects/rna_seq_workflow/resources/rna_seq_foxy/reads

#Absolute path to the reference genome fasta
ref_genome: /home/nanopore/projects/rna_seq_workflow/resources/rna_seq_foxy/genome/GCF_000149955.1/GCF_000149955.1_ASM14995v2_genomic.fna

#The ID for this analyis run
run id: 20240716_FOXY

#Absolute path to the genome annotation file (GTF) 
gtf: /home/nanopore/projects/rna_seq_workflow/resources/rna_seq_foxy/genome/GCF_000149955.1/genomic.gtf

#Sample info file 
sample_info: /home/nanopore/projects/rna_seq_workflow/resources/rna_seq_foxy/20240716_FOXY_info.tsv

#Contrast .csv file containing a "treatment" column and a "control" column specifying what conditions should be contrasted. 
contrast :  /home/nanopore/projects/rna_seq_workflow/resources/rna_seq_foxy/foxy_contrast.csv

#Absoulte path to the reference amino acid sequences
protein_fasta: /home/nanopore/projects/rna_seq_workflow/resources/rna_seq_foxy/genome/GCF_000149955.1/protein.faa

#EGGNOG-MAPPER V2 results (Optional)
eggnog_results: /home/nanopore/projects/rna_seq_workflow/resources/rna_seq_foxy/MM_0t_4hjca.emapper.annotations.tsv


#PARAMETERS

#Strandness ["",0] for Unstranded, ["FR",1] for Stranded or ["RF",2] for Reverse Stranded
Strandness: ["RF",2]

GO_terms: yes