### CONFIG for amplicon workflow ###
# Note: This is a sample configuration file. Adjust the paths and parameters as needed.

### General settings ###

# Threads for parallel processing
threads: 40 # For stability, calculate threads as 2x the available cores (max cores=32)

# Run ID for the analysis
run_id: "16S_compost_lara_SUP"

# Path to the directory containing the barcode folders
reads_dir: "/mnt/d/MinKNOW/experiments/16S_compost_lara/16S_compost/20240408_1737_MN45285_FAY62232_6b520ec0/fast5_pass/basecalling/pass"

### Concat, PCR-Primer trimming and inital filtering ###

# Minimum and maximum length of reads to keep
min_length: 1000
max_length: 2000
# Minimum quality score for filtering (10 = 10% error rate, 20 = 1% error rate)
min_quality: 10

# PCR primer sequences to trim from the reads in fasta format (header form: [id]_front/rear type=primer) (OPTIONAL)
#primer_fasta: "/home/nanopore/projects/amplicon_workflow/resources/primer_seq/27F_1492R.fa"

### Chimera removal ###

# Denovo or reference based chimera removal
chimera_removal: "denovo"  # Options: "denovo", "ref"
# Path to the reference database for chimera removal (OPTIONAL, required if chimera_removal is set to "ref")
chimera_db: "/home/nanopore/projects/amplicon_workflow/resources/emu_db/species_taxid.fasta"

### Emu classification ###

taxonomic_rank: "species"  # Options: "species", "genus", "family", "order", "class", "phylum", "superkingdom"

## Path to the reference database
# Note that some prebuild alternative databases (e.g. SILVA) are available through the emu repository (https://github.com/treangenlab/emu).
# The custom database folder should contain sequences.fasta, taxonomy.tsv (sequence id to taxid mapping) and species_taxid.tsv (taxid to lineage mapping)). 
# See /home/nanopore/projects/amplicon_workflow/resources/custom_dbs/pr2_510_emu/ for an example.
reference_db_emu: "/home/nanopore/projects/amplicon_workflow/resources/emu_db" 

# Minimal relative abundance of a taxon to be included in the final report (0.01 = 1% abundance)
min_abundance: 0.0001
