#INPUT

genome_assembly: /home/nanopore/projects/simona/cloro_assembly/flye_assembly/clonostachys_rosea.fasta

rna_reads_directory : 
#or
SRA_accession: SRR26555584

Run ID: clonostachys_rosea

DFAM taxon: fungi

eggnog_results: /home/nanopore/projects/genome_annotation/resources/clonostachys_rosea/MM_b_dstdr_.emapper.annotations.tsv

GO_terms: "yes"

threads: 8 

# Causes bug in BRAKER!
Fungi: 
