#INPUT

genome_assembly: /home/marc/projects/genome_annotation/resources/genome_assembly/fusarium_oxysporum/ncbi_dataset/data/GCF_013085055.1/GCF_013085055.1_ASM1308505v1_genomic.fna

rna_reads_directory : /home/marc/projects/rna_seq_workflow/resources/rna_seq_foxy/reads

Run ID: fusarium_oxysporum

DFAM taxon: eukaryota

# Causes bug in BRAKER
#Fungi: 

#PARAMETERS

Threads: 4