from snakemake.utils import min_version
# Check if the version of snakemake is at least 8.11.3
min_version("8.11.3")
from pathlib import Path
import pandas as pd

# Load the configuration file
configfile: "config/config.yaml"

# Define the samples
SAMPLES = glob_wildcards(config["seq_dir"]+"/{sample}_{group}.fastq.gz")

# Define the contrast conditions
def contrast_conditions(config_contrast):
    if not Path(config_contrast).exists():
        raise FileNotFoundError(f"Contrast file '{config_contrast}' not found.")
    contrast_df = pd.read_csv(config_contrast)
    if contrast_df.empty or contrast_df.shape[1] < 2:
        raise ValueError("Contrast file is empty or has fewer than two columns.")
    contrast_list = ["_vs_".join(pair) for pair in contrast_df.values.tolist()]
    return contrast_list

# Define the variables
CONTRAST = contrast_conditions(config["contrast"])
RUN_ID = config["run id"]

# Define the wildcard constraints
wildcard_constraints:
    contrast = ".*_vs_.*",
    run_id = config["run id"]

# Define the final output files
def get_final_output():
    # Check if samples are detected
    if not SAMPLES:
        raise ValueError("No samples detected. Check 'seq_dir' in config.")
    
    final_output = [
        expand("results/{run_id}/fastqc/{sample}_{group}_fastqc.{ext}",
               run_id=RUN_ID, sample=set(SAMPLES.sample), group=set(SAMPLES.group), ext=["html", "zip"]),]

    # Add DEG analysis files to final output
        final_output.extend([
            expand("results/{run_id}/hisat2_align/{sample}.sortedByCoord.out.bam", run_id=RUN_ID, sample=set(SAMPLES.sample)),
            expand("results/{run_id}/feature_counts/{run_id}_counts.txt", run_id=RUN_ID),
            expand("results/{run_id}/feature_counts/mod_{run_id}_counts.csv", run_id=RUN_ID),
            expand("results/{run_id}/DEG_analysis/{run_id}_dds.rds", run_id=RUN_ID),
            expand("results/{run_id}/DEG_analysis/deg_{contrast}.csv", run_id=RUN_ID, contrast=CONTRAST),
        ])
    # Add DEG visualization files to final output
        final_output.extend([
            expand("results/{run_id}/DEG_analysis/plots/heatmap.svg", run_id=RUN_ID),
            expand("results/{run_id}/DEG_analysis/plots/{contrast}_volcano.pdf", run_id=RUN_ID, contrast=CONTRAST),
        ])
    
    return final_output

# Define the rule to generate the final output
rule all:
    input:
        get_final_output()


# Include the rules
include:    "rules/01_fastqc.smk"

include:    "rules/02_hisat2_index.smk"
include:    "rules/03_hisat2_align.smk"
include:    "rules/04_featureCounts.smk"
include:    "rules/05_deseq2_prep.smk"
include:    "rules/06_deseq2.smk"

include:    "rules/07_volcano.smk"
include:    "rules/08_heatmap.smk"





