seq_dir: "/home/marc/data/rna_seq_test/test2/reads"
ref_genome: "/home/marc/data/rna_seq_test/test2/reference_genome/GCF_000001735.4_TAIR10.1_genomic.fna"
Run ID: "Arabidopsis_thaliana"
gtf: "/home/marc/data/rna_seq_test/test2/gtf/ncbi_dataset/data/GCF_000001735.4/genomic.gtf"
results_dir: "/home/marc/results/test2"


Trimming: "n"
adapter_r1: "A"
adapter_r2: "A"
threads:  3

#Choose between STAR (computational intensive! Use HPC) or HISAT2
Alignment_tool: "HISAT2"

#Optional: Choose a quality cutoff value for your reads
quality_cutoff: ""