# Wishlist:
# - Single-end reads support
# - Download reference genome
# - qc after trimming
# - make trimming optional
# - option for gz and raw input.fastq

import pandas as pd 
import numpy as np

# Define input directory and sample names from config file
configfile: "config.yaml"

seq_dir = config["seq_dir"]
results_dir = config["results_dir"]
samples = glob_wildcards(seq_dir+"/{sample}_{pos}.fastq")
ref_genome = config["ref_genome"]
run_id = config["Run ID"]
trimming = config["Trimming"]
Alignment_tool = config["Alignment_tool"]



# Define the final output rule
rule all:
    input:
        expand(results_dir+"/{aligner}/alignment/{sample}/{sample}.sortedByCoord.out.bam", sample=set(samples.sample), aligner=Alignment_tool),
        f"{results_dir}/feature_counts/{run_id}/{run_id}_counts.txt",
       # f"{results_dir}/feature_counts/{run_id}/mod_{run_id}_counts.csv"


# Rule to run FastQC on all samples
rule fastqc:
    input: 
        seq = seq_dir+"/{sample}_{pos}.fastq"
    output:
        html = results_dir+"/fastqc/{sample}_{pos}_fastqc.html",
        zip_file = results_dir+"/fastqc/{sample}_{pos}_fastqc.zip"   
    params:
        results_dir = results_dir+"/fastqc"
    threads:
        config["threads"]
    shell:"""fastqc -t {threads} {input.seq} --outdir {params}"""

#Rule to run cutadapt on all paired-end reads
rule cutadapt:
    input:
        seq_r1 = seq_dir+"/{sample}_R1.fastq" if trimming == "y" else "",
        seq_r2 = seq_dir+"/{sample}_R2.fastq" if trimming == "y" else ""
    output:
        trimmed_r1 = results_dir+"/cutadapt/trim_{sample}_R1.fastq",
        trimmed_r2 = results_dir+"/cutadapt/trim_{sample}_R2.fastq"
    params:
        adapter_r1 = config["adapter_r1"],
        adapter_r2 = config["adapter_r2"],
        quality_cutoff = "-q "+config["quality_cutoff"] if config["quality_cutoff"] else ""
    threads:
        config["threads"]

    shell:  """cutadapt -j 2 {params.quality_cutoff} -a {params.adapter_r1} -A {params.adapter_r2} -o {output.trimmed_r1} -p {output.trimmed_r2} {input.seq_r1} {input.seq_r2}"""

if Alignment_tool == "HISAT2":
    rule hisat2_index:
        input:
            ref_genome
        output:
            index_file = results_dir+"/HISAT2/index/"+run_id+"/"+run_id+".1.ht2"
        params:
            index_dir = directory(results_dir+"/HISAT2/index/"+run_id),
            basename = results_dir+"/HISAT2/index/"+run_id+"/"+run_id
        threads:
            config["threads"]

        shell: """mkdir {params.index_dir} && hisat2-build -p {threads} {input} {params.basename}"""       

    rule hisat2_align:
        input:
            r1 = results_dir+"/cutadapt/trim_{sample}_R1.fastq" if trimming == "y" else seq_dir+"/{sample}_R1.fastq",
            r2 = results_dir+"/cutadapt/trim_{sample}_R2.fastq" if trimming == "y" else seq_dir+"/{sample}_R2.fastq"
        output:
            bam_file = results_dir+"/{aligner}/alignment/"+run_id+"/{sample}.sortedByCoord.out.bam"
        log:
            summary = results_dir+"/{aligner}/alignment/"+run_id+"/{sample}_summary.log",
            metrics = results_dir+"/{aligner}/alignment/"+run_id+"/{sample}_metrics.log"
        params:
            indexed_genome_prefix = results_dir+"/{aligner}/index/"+run_id+"/"+run_id
        threads:
            config["threads"]

        shell: """hisat2 -p {threads} -x {params.indexed_genome_prefix} -1 {input.r1} -2 {input.r2} --summary-file {log.summary} --met-file {log.metrics} | samtools sort -o {output.bam_file}"""

elif Alignment_tool == "STAR":
    rule star_index:
        input:
            ref_genome
        output:
            directory(results_dir+"/STAR/index/"+run_id)
        threads:
            config["threads"]

        shell: """STAR --runMode genomeGenerate --genomeDir {output} --genomeFastaFiles {input} """
    
    rule star_align:
        input:
            r1 = results_dir+"/cutadapt/trim_{sample}_R1.fastq" if trimming == "y" else seq_dir+"/{sample}_R1.fastq",
            r2 = results_dir+"/cutadapt/trim_{sample}_R2.fastq" if trimming == "y" else seq_dir+"/{sample}_R2.fastq",
            indexed_genome_dir = results_dir+"/{aligner}/index/"+run_id
        output:
            bam_file = results_dir+"/{aligner}/alignment/"+run_id+"/{sample}.sortedByCoord.out.bam"
        params:
            output_prefix = results_dir+"/{aligner}/alignment/{sample}/{sample}"

        threads: config["threads"]

        shell: """STAR runMode alignReads --runThreadN {threads} --genomeDir {input.indexed_genome} --readFilesIn {input.r1}, {input.r2} --readFilesCommand zcat --outFileNamePrefix {params.output_prefix} --outSAMtype BAM SortedByCoordinate"""

rule featureCounts:
    input:
        gtf = config["gtf"],
        bam_files = expand(results_dir+"/{aligner}/alignment/"+run_id+"/{sample}.sortedByCoord.out.bam", aligner=Alignment_tool, sample=set(samples.sample))
    output:
        counts_table = f"{results_dir}/feature_counts/{run_id}/{run_id}_counts.txt"

    threads: config["threads"]

    shell: """featureCounts -T {threads} -p -t "gene" --extraAttributes "gene" -a {input.gtf} -o {output.counts_table} {input.bam_files}"""

rule deseq2_prep:
    input:
        counts_table = f"{results_dir}/feature_counts/{run_id}/{run_id}_counts.txt",
        sample_info = f"{seq_dir}/{run_id}_info.txt"
    output:
        prep_counts_table = f"{results_dir}/feature_counts/{run_id}/mod_{run_id}_counts.csv",
        mapID = f"{results_dir}/feature_counts/{run_id}/{run_id}_mapid.csv"
    log:
        filtered = f"{results_dir}/feature_counts/{run_id}/abundance_filter.log"
    run:
        #Read in counts table
        counts_df = pd.read_csv(input.counts_table, sep= "\t", header=1)

        #Filters out genes with less than 10 counts across all samples
        unfiltered_counts = len(counts_df.index)
        counts_df = counts_df[counts_df.iloc[:, 7:].sum(axis=1) >= 10]
        filtered_counts = len(counts_df.index)
        with open(log.filtered, "w") as log_file:
            log_file.write(f"From {unfiltered_counts} genes, {filtered_counts} occured at least 10 times across samples and where used for subsequent analysis")
        
        #Makes a copy of the "Geneid" and "gene" column, which can be used to convert Gene IDs to Gene symbols for GO-Analysis and GSEA)
        symbols_df = counts_df.filter(items=["Geneid","gene"])
        symbols_df.to_csv(output.mapID, index=False)
        #Drop unnecessary columns that would stop DESeq2 from correctly identifying the count table
        counts_df = counts_df.drop(["Chr","Start","End","Strand","Length","gene"], axis=1)
       

        #Replace "realpath" for sample id as column name
        for col_name in counts_df.columns:
            new_col_name = Path(col_name).stem.removesuffix(".sortedByCoord.out")
            counts_df.rename(columns={col_name: new_col_name}, inplace=True)

        #Read in sample information (e.g. "treated" or "control")
        sample_info_df = pd.read_csv(input.sample_info, sep="\t", header=0)
        #Put sample ids from sample information in a list
        sorted_sample_list = sample_info_df["sample"].tolist()
        sorted_sample_list.insert(0, "Geneid") 

        #Orders the columns based on the order of sample ids in the sample information (Requiered by DESeq2)
        counts_df = counts_df[sorted_sample_list]

        counts_df.to_csv(output.prep_counts_table, index=False)

rule deseq2:
    input:
        prep_counts_table = f"{results_dir}/feature_counts/{run_id}/mod_{run_id}_counts.csv",
        sample_info = f"{seq_dir}/{run_id}_info.txt",
        mapID = f"{results_dir}/feature_counts/{run_id}/{run_id}_mapid.csv"
    output:
        deg_table = f"{results_dir}/DEG_analysis/{run_id}/{run_id}_deseq2_results.csv",
        filt_deg_table = f"{results_dir}/DEG_analysis/{run_id}/{run_id}_sig_deseq2_results.csv",
        mod_deg_table = f"{results_dir}/DEG_analysis/{run_id}/{run_id}_mod_deseq2_results.csv",
        disp_plot = f"{results_dir}/DEG_analysis/{run_id}/{run_id}_dispersion_plot.pdf",
        pca_plot = f"{results_dir}/DEG_analysis/{run_id}/{run_id}_pca_plot.pdf"
    conda:
        "deg_analysis.yaml"
    script:
        "deseq2_workflow.R"

rule volcano:
    input:
        deg_table = f"{results_dir}/DEG_analysis/{run_id}/{run_id}_deseq2_results.csv",
        filt_deg_table = f"{results_dir}/DEG_analysis/{run_id}/{run_id}_deseq2_results_padj005.csv",
        mod_deg_table = f"{results_dir}/DEG_analysis/{run_id}/{run_id}_mod_deseq2_results.csv"
    output:
        volcano_plot = f"{results_dir}/DEG_analysis/{run_id}/{run_id}_volcano_plot.pdf",
    conda:
        "enhanced_volcano.yaml"
    script:
        "volcano_plotting.R"
