from snakemake.utils import min_version
min_version("8.11.3")
from pathlib import Path
import pandas as pd

configfile: "config/config.yaml"

SAMPLES = glob_wildcards(config["seq_dir"]+"/{sample}_{group}.fastq.gz")

def contrast_conditions(config_contrast):
    contrast_df = pd.read_csv(config_contrast)
    contrast_list = contrast_df.values.tolist()
    contrast_list = ["_vs_".join(pair) for pair in contrast_list]
    return contrast_list

CONTRAST = contrast_conditions(config["contrast"])

wildcard_constraints:
    contrast=".*_vs_.*"

def get_final_output():
    final_output = expand("results/fastqc/{run_id}/{sample}_{group}_fastqc.{ext}", 
    run_id=config["Run ID"], sample=set(SAMPLES.sample), group=set(SAMPLES.group), ext=["html","zip"]
    )
    # final_output.append(expand("results/hisat2_align/{run_id}/{sample}.sortedByCoord.out.bam", run_id=config["Run ID"], sample=set(SAMPLES.sample)))
    # final_output.append(expand("results/feature_counts/{run_id}/{run_id}_counts.txt", run_id=config["Run ID"]))
    # final_output.append(expand("results/feature_counts/{run_id}/mod_{run_id}_counts.csv", run_id=config["Run ID"]))
    final_output.append(expand("results/DEG_analysis/{run_id}/{run_id}_dds.rds", run_id=config["Run ID"]))
    final_output.append(expand("results/DEG_analysis/{run_id}/{run_id}_{contrast}.csv", run_id=config["Run ID"], contrast=CONTRAST))
    final_output.append(expand("results/DEG_analysis/{run_id}/plots/{run_id}_heatmap.pdf", run_id=config["Run ID"]))
    final_output.append(expand("results/DEG_analysis/{run_id}/plots/{run_id}_{contrast}_volcano.pdf", run_id=config["Run ID"], contrast=CONTRAST))
    final_output.append(expand("resources/{run_id}_gtf_db", run_id=config["Run ID"]))
    final_output.append(expand("results/DEG_analysis/{run_id}/{contrast}/main_{run_id}_{contrast}.csv", run_id=config["Run ID"], contrast=CONTRAST))
    final_output.append(expand("results/DEG_analysis/{run_id}/{contrast}/{run_id}_{contrast}.aa", run_id=config["Run ID"], contrast=CONTRAST))
    final_output.append(expand("results/functional_annotations/{run_id}/interproscan/{run_id}_{contrast}.gff3", run_id=config["Run ID"], contrast=CONTRAST))
    final_output.append(expand("resources/{run_id}/{run_id}_{contrast}_interpro_results_db", run_id=config["Run ID"], contrast=CONTRAST))
    final_output.append(expand("results/functional_annotations/interproscan/{run_id}/{contrast}/{run_id}_{contrast}_interpro_annotations.csv", run_id=config["Run ID"], contrast=CONTRAST))
    if config["eggnog_results"]:
        final_output.append(expand("results/functional_annotations/{run_id}/{contrast}/{run_id}_combined_annotations.csv", run_id=config["Run ID"], contrast=CONTRAST))
    return final_output

rule all:
    input:
        get_final_output()


include:    "rules/fastqc.smk"

if config["Trimming"] == "yes":
    include:    "rules/cutadapt.smk"

# include:    "rules/hisat2_index.smk"
# include:    "rules/hisat2_align.smk"
# include:    "rules/featureCounts.smk"
include:    "rules/deseq2_prep.smk"
include:    "rules/deseq2.smk"
include:    "rules/volcano.smk"
include:    "rules/heatmap.smk"
include:    "rules/gtf_db.smk"
include:    "rules/protein_seq_extract.smk"
include:    "rules/interproscan.smk"
include:    "rules/interpro_annotations.smk"

if config["eggnog_results"]:
    include: "rules/eggnog_annotations.smk"


