#2023_08_18:    Everything works until creation of counttable, you have to check every rule after that.
#               Alignmentrate is a little fishy (~60% unique concordant maps)
#               Features can only be assgined to ~50% of them, unusually low?
#               Reads seem to be reverse stranded (-> highest assignment rate in featurecounts)

from snakemake.utils import min_version
min_version("7.25")

configfile: "config/config.yaml"

samples = glob_wildcards(config["seq_dir"]+"/{sample}_{group}.fastq")

rule all:
    input:
        expand("/home/marc/projects/rna_seq_workflow/results/fastqc/{sample}_{group}_fastqc.{ext}", sample=set(samples.sample), group=["R1","R2"], ext=["html","zip"]),
        #expand("/home/marc/projects/rna_seq_workflow/results/{aligner}_align/fr_strandness/{sample}.sortedByCoord.out.bam", sample=set(samples.sample), aligner=config["Aligner"]),
        #expand("/home/marc/projects/rna_seq_workflow/results/feature_counts/{run_id}_counts.txt", run_id=config["Run ID"]),
        expand("/home/marc/projects/rna_seq_workflow/results/DEG_analysis/{run_id}_deseq2_results.csv", run_id=config["Run ID"]),
        expand("/home/marc/projects/rna_seq_workflow/results/DEG_analysis/{run_id}_deseq2_results_LFC.csv", run_id=config["Run ID"]),
        expand("/home/marc/projects/rna_seq_workflow/results/DEG_analysis/{run_id}_sig_deseq2_results.csv", run_id=config["Run ID"]),
        expand("/home/marc/projects/rna_seq_workflow/results/DEG_analysis/{run_id}_mod_deseq2_results.csv", run_id=config["Run ID"]),
        expand("/home/marc/projects/rna_seq_workflow/results/DEG_analysis/{run_id}_normalized_counts.csv", run_id=config["Run ID"]),
        expand("/home/marc/projects/rna_seq_workflow/results/DEG_analysis/plots/{run_id}_dispersion_plot.pdf", run_id=config["Run ID"]),
        expand("/home/marc/projects/rna_seq_workflow/results/DEG_analysis/plots/{run_id}_pca_plot.pdf", run_id=config["Run ID"]),
        expand("/home/marc/projects/rna_seq_workflow/results/DEG_analysis/plots/{run_id}_heatmap.pdf", run_id=config["Run ID"]),
        expand("/home/marc/projects/rna_seq_workflow/results/DEG_analysis/plots/{run_id}_volcano_plot.pdf", run_id=config["Run ID"]),
       # expand("/home/marc/projects/rna_seq_workflow/results/GSEA/{run_id}_gsea_gobp.csv", run_id=config["Run ID"]),
        
include:    "rules/fastqc.smk"

if config["Trimming"] == "yes":
    include:    "rules/cutadapt.smk"

include:    "rules/hisat2_index.smk"
include:    "rules/hisat2_align.smk"
include:    "rules/featureCounts.smk"
include:    "rules/deseq2_prep.smk"
include:    "rules/deseq2.smk"
include:    "rules/volcano.smk"
include:    "rules/heatmap.smk"
#include:    "rules/gsea.smk"

        


# seq_dir = config["seq_dir"]
# samples = glob_wildcards(seq_dir+"/{sample}_{pos}.fastq")
# # ref_genome = config["ref_genome"]
# # run_id = config["Run ID"]
# # trimming = config["Trimming"]
# # Alignment_tool = config["Alignment_tool"]


#Define input directory and sample names from config file

# # Define the final output rule
# #rule all:
#  #   input:
#   #      expand(results_dir+"/{aligner}/alignment/{sample}/{sample}.sortedByCoord.out.bam", sample=set(samples.sample), aligner=Alignment_tool),
#    #     f"{results_dir}/feature_counts/{run_id}/{run_id}_counts.txt",
#        # f"{results_dir}/feature_counts/{run_id}/mod_{run_id}_counts.csv"


# # Rule to run FastQC on all samples
# rule fastqc:
#     input: 
#         seq = seq_dir+"/{sample}_{pos}.fastq"
#     output:
#         html = results_dir+"/fastqc/{sample}_{pos}_fastqc.html",
#         zip_file = results_dir+"/fastqc/{sample}_{pos}_fastqc.zip"  

#     params:
#         results_dir = results_dir+"/fastqc"

#     threads:
#         config["threads"]
#     conda:
#         "fastqc.yaml"

#     shell:"""fastqc -t {threads} {input.seq} --outdir {params}"""

# #Rule to run cutadapt on all paired-end reads
# rule cutadapt:
#     input:
#         seq_r1 = seq_dir+"/{sample}_R1.fastq" if trimming == "y" else "",
#         seq_r2 = seq_dir+"/{sample}_R2.fastq" if trimming == "y" else ""
#     output:
#         trimmed_r1 = results_dir+"/cutadapt/trim_{sample}_R1.fastq",
#         trimmed_r2 = results_dir+"/cutadapt/trim_{sample}_R2.fastq"
#     params:
#         adapter_r1 = config["adapter_r1"],
#         adapter_r2 = config["adapter_r2"],
#         quality_cutoff = "-q "+config["quality_cutoff"] if config["quality_cutoff"] else ""
#     threads:
#         config["threads"]
#     conda:
#         "cutadapt.yaml"
#     shell:  """cutadapt -j 2 {params.quality_cutoff} -a {params.adapter_r1} -A {params.adapter_r2} -o {output.trimmed_r1} -p {output.trimmed_r2} {input.seq_r1} {input.seq_r2}"""

# if Alignment_tool == "HISAT2":
#     rule hisat2_index:
#         input:
#             ref_genome
#         output:
#             index_file = results_dir+"/HISAT2/index/"+run_id+"/"+run_id+".1.ht2"
#         params:
#             index_dir = directory(results_dir+"/HISAT2/index/"+run_id),
#             basename = results_dir+"/HISAT2/index/"+run_id+"/"+run_id
#         threads:
#             config["threads"]
#         conda:
#             "hisat2.yaml"
#         shell: """mkdir {params.index_dir} && hisat2-build -p {threads} {input} {params.basename}"""       

#     rule hisat2_align:
#         input:
#             r1 = results_dir+"/cutadapt/trim_{sample}_R1.fastq" if trimming == "y" else seq_dir+"/{sample}_R1.fastq",
#             r2 = results_dir+"/cutadapt/trim_{sample}_R2.fastq" if trimming == "y" else seq_dir+"/{sample}_R2.fastq"
#         output:
#             bam_file = results_dir+"/{aligner}/alignment/"+run_id+"/{sample}.sortedByCoord.out.bam"
#         log:
#             summary = results_dir+"/{aligner}/alignment/"+run_id+"/{sample}_summary.log",
#             metrics = results_dir+"/{aligner}/alignment/"+run_id+"/{sample}_metrics.log"
#         params:
#             indexed_genome_prefix = results_dir+"/{aligner}/index/"+run_id+"/"+run_id
#         threads:
#             config["threads"]
#         conda:
#             "hisat2.yaml"
#         shell: """hisat2 -p {threads} -x {params.indexed_genome_prefix} -1 {input.r1} -2 {input.r2} --summary-file {log.summary} --met-file {log.metrics} | samtools sort -o {output.bam_file}"""

# elif Alignment_tool == "STAR":
#     rule star_index:
#         input:
#             ref_genome
#         output:
#             directory(results_dir+"/STAR/index/"+run_id)
#         threads:
#             config["threads"]
#         conda:
#             "star.yaml"
#         shell: """STAR --runMode genomeGenerate --genomeDir {output} --genomeFastaFiles {input} """
    
#     rule star_align:
#         input:
#             r1 = results_dir+"/cutadapt/trim_{sample}_R1.fastq" if trimming == "y" else seq_dir+"/{sample}_R1.fastq",
#             r2 = results_dir+"/cutadapt/trim_{sample}_R2.fastq" if trimming == "y" else seq_dir+"/{sample}_R2.fastq",
#             indexed_genome_dir = results_dir+"/{aligner}/index/"+run_id
#         output:
#             bam_file = results_dir+"/{aligner}/alignment/"+run_id+"/{sample}.sortedByCoord.out.bam"
#         params:
#             output_prefix = results_dir+"/{aligner}/alignment/{sample}/{sample}"
#         threads: config["threads"]
#         conda:
#             "star.yaml"

#         shell: """STAR runMode alignReads --runThreadN {threads} --genomeDir {input.indexed_genome} --readFilesIn {input.r1}, {input.r2} --readFilesCommand zcat --outFileNamePrefix {params.output_prefix} --outSAMtype BAM SortedByCoordinate"""

# rule featureCounts:
#     input:
#         gtf = config["gtf"],
#         bam_files = expand(results_dir+"/{aligner}/alignment/"+run_id+"/{sample}.sortedByCoord.out.bam", aligner=Alignment_tool, sample=set(samples.sample))
#     output:
#         counts_table = f"{results_dir}/feature_counts/{run_id}/{run_id}_counts.txt"

#     threads: config["threads"]
#     conda:
#         "subread.yaml"

#     shell: """featureCounts -T {threads} -p --extraAttributes "gene" -a {input.gtf} -o {output.counts_table} {input.bam_files}"""

# rule deseq2_prep:
#     input:
#         counts_table = f"{results_dir}/feature_counts/{run_id}/{run_id}_counts.txt",
#         sample_info = f"{seq_dir}/{run_id}_info.txt"
#     output:
#         prep_counts_table = f"{results_dir}/feature_counts/{run_id}/mod_{run_id}_counts.csv",
#         mapID = f"{results_dir}/feature_counts/{run_id}/{run_id}_mapid.csv"
#     log:
#         filtered = f"{results_dir}/feature_counts/{run_id}/abundance_filter.log"
#     conda:
#         "deseq2_prep.yaml"
#     script:
#         "deseq2_prep.py"

# rule deseq2:
#     input:
#         prep_counts_table = f"{results_dir}/feature_counts/{run_id}/mod_{run_id}_counts.csv",
#         sample_info = f"{seq_dir}/{run_id}_info.txt",
#         mapID = f"{results_dir}/feature_counts/{run_id}/{run_id}_mapid.csv"
#     output:
#         deg_table = f"{results_dir}/DEG_analysis/{run_id}/{run_id}_deseq2_results.csv",
#         filt_deg_table = f"{results_dir}/DEG_analysis/{run_id}/{run_id}_sig_deseq2_results.csv",
#         mod_deg_table = f"{results_dir}/DEG_analysis/{run_id}/{run_id}_mod_deseq2_results.csv",
#         normalized_counts = f"{results_dir}/DEG_analysis/{run_id}/{run_id}_normalized_counts.csv",
#         disp_plot = f"{results_dir}/DEG_analysis/{run_id}/plots/{run_id}_dispersion_plot.pdf",
#         pca_plot = f"{results_dir}/DEG_analysis/{run_id}/plots/{run_id}_pca_plot.pdf"
#     conda:
#         "deg_analysis.yaml"
#     script:
#         "deseq2_workflow.R"

# rule volcano:
#     input:
#         mod_deg_table = f"{results_dir}/DEG_analysis/{run_id}/{run_id}_mod_deseq2_results.csv",
#     output:
#         volcano_plot = f"{results_dir}/DEG_analysis/{run_id}/plots/{run_id}_volcano_plot.pdf",
#     conda:
#         "enhanced_volcano.yaml"
#     script:
#         "volcano_plotting.R"

# rule heatmap:
#     input:
#         sample_info = f"{seq_dir}/{run_id}_info.txt",
#         mod_deg_table = f"{results_dir}/DEG_analysis/{run_id}/{run_id}_mod_deseq2_results.csv",
#         normalized_counts = f"{results_dir}/DEG_analysis/{run_id}/{run_id}_normalized_counts.csv",
#     output:
#         heatmap_plot = f"{results_dir}/DEG_analysis/{run_id}/plots/{run_id}_heatmap.pdf",
#     conda:
#         "complex_heatmap.yaml"
#     script:
#         "heatmap_plotting.R"

# rule gsea:
#     input:
#         mod_deg_table = f"{results_dir}/DEG_analysis/{run_id}/{run_id}_mod_deseq2_results.csv",
#     output:
#         gsea_results = f"{results_dir}/DEG_analysis/gsea/{run_id}/{run_id}_gsea_gobp.csv",
#     params:
#         seed = 27
#     conda:
#         "gsea.yaml"
#     script:
#         "gsea.py"

# rule mulitqc:
#     input:
